# This is a basic workflow to help you get started with Actions

name: TgAI CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Connesione all'SSH e avvio del bot
      uses: appleboy/ssh-action@master
      #environment: main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/bot-api/
          git pull origin main
          nohup screen -AmdS bot dotnet run --project ./TgAI --configuration Release